add_newline = false

[git_status]
disabled = true

[git_state]
disabled = false

[package]
disabled = true
style = "orange"

[git_commit]
commit_hash_length = 7
tag_disabled = false
only_detached = true
format = '[\($tag\)]($style)'
disabled = false

[battery]
disabled = true

[python]
disabled = false
format = '[${symbol}${pyenv_prefix}(\($virtualenv\) )]($style)'

[cmake]
disabled = true

[git_metrics]
disabled = false
format = '([+$added]($added_style)) ([-$deleted]($deleted_style)) '

[aws]
disabled = true

[docker_context]
disabled = true

[git_branch]
disabled = false
style = "lavender"

[gcloud]
disabled = true

[username]
disabled = false
show_always = true

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"

[directory]
truncation_length = 4
truncation_symbol = "…/"
style = "fern"


[perl]
style = "green"

[swift]
style = "red"

[terraform]
style = "purple"

[palettes.moonfly]
fern = "#87d787"
lavender = "#adadf3"
orange = "#f09479"
red = "#f07496"
