add_newline = false

# [character]
# success_symbol = '[ #](bold green)'
# error_symbol = "[ x](bold red)"
# vicmd_symbol = "[ V](bold green)"

[git_status]
disabled = true

[git_state]
disabled = false

[package]
disabled = true

[git_commit]
commit_hash_length = 7
tag_disabled = false
only_detached = true
format = '[\($tag\)]($style)'
disabled = false

[battery]
disabled = true

[python]
disabled = false
format = '[${symbol}${pyenv_prefix}(\($virtualenv\) )]($style)'

[cmake]
disabled = true

[git_metrics]
disabled = false
format = '([+$added]($added_style)) ([-$deleted]($deleted_style)) '


[aws]
disabled = true

[docker_context]
disabled = true

[git_branch]
disabled = false

