[config]
reload_apps = false

[templates.waybar]
input_path = '~/.config/matugen/templates/colors-waybar.css'
output_path = '~/.cache/colors-waybar.css'

[templates.hyprlock-colors]
input_path = '~/.config/matugen/templates/hyprlock-colors.conf'
output_path = '~/.cache/hyprlock-colors.conf'
