# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = float, class:zen, title:Picture-in-Picture
windowrule = pin, class:zen, title:Picture-in-Picture
windowrule = persistentsize, class:zen, title:Picture-in-Picture
windowrule = noinitialfocus, class:zen, title:Picture-in-Picture
windowrule = content video, class:zen, title:Picture-in-Picture
windowrule = move 81% 81%, class:zen, title:Picture-in-Picture
windowrule = opacity override 1.0 override 1.0 override 1.0,class:zen,title:Picture-in-Picture
windowrule = opacity override 1.0 override 1.0 override 1.0,class:zen,title:.+Twitch.+
windowrule = opacity override 1.0 override 1.0 override 1.0,class:zen,title:.+YouTube.+
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window


# layerrule = blur,vicinae
# layerrule = ignorealpha 0, vicinae

# disable fade animation for vicinae only
layerrule = noanim, vicinae
