exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprpaper
exec-once = swaync
exec-once = waybar
exec-once = hypridle

# Network Applet
exec-once = nm-applet --indicator

# Firewall Applet
exec-once = sleep 2 && firewall-applet

# bluetooth applet
exec-once = blueman-applet
