exec-once = systemctl --user start hyprpolkitagent
# exec-once = hyprpaper
exec-once = swww-daemon
exec-once = swaync
exec-once = waybar
exec-once = hypridle
exec-once = ~/.config/hypr/scripts/wallpaper_swww.sh

# Network Applet
exec-once = nm-applet --indicator

# Firewall Applet
exec-once = sleep 2 && firewall-applet

# bluetooth applet
exec-once = blueman-applet
exec-once = vicinae server
